name: Playwright Docker Tests

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow to run tests manually from GitHub Actions tab

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-playwright-tests .

      - name: Run tests in Docker
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "HTTP_PASSWORD=${{ secrets.HTTP_PASSWORD }}" >> .env
          echo "HTTP_USER=${{ secrets.HTTP_USER }}" >> .env
          echo "CUSTOMER_EMAIL=${{ secrets.CUSTOMER_EMAIL }}" >> .env
          echo "CUSTOMER_PASSWORD=${{ secrets.CUSTOMER_PASSWORD }}" >> .env

          docker run --rm --env-file .env -e CI=true \
          -v $(pwd)/playwright-report:/app/playwright-report \
          -v $(pwd)/test-results:/app/test-results \
          my-playwright-tests

      - name: Upload Report
        if: always() # Upload report even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'